# Generated by Django 5.1.5 on 2025-01-26 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bairro_cidade', to='Cidade.cidade')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
