# Generated by Django 5.1.5 on 2025-01-26 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cargo', '0001_initial'),
        ('Pessoa', '0001_initial'),
        ('Setor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lotacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=5)),
                ('data_admissao', models.DateField()),
                ('data_demissional', models.DateField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotacao_cargo', to='Cargo.cargo')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotacao_pessoa', to='Pessoa.pessoa')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotacao_setor', to='Setor.setor')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
