# Generated by Django 5.1.5 on 2025-01-26 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bairro', '0001_initial'),
        ('Pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('logradouro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('complemento', models.CharField(max_length=100)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='endereco_bairro', to='Bairro.bairro')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='endereco_pessoa', to='Pessoa.pessoa')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
