# Generated by Django 5.1.5 on 2025-01-26 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pessoa', '0001_initial'),
        ('Tipo_Contato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoContatoPessoa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contato', models.CharField(max_length=45)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tcp_pessoa', to='Pessoa.pessoa')),
                ('tipo_contato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tcp_tc', to='Tipo_Contato.tipocontato')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
