# Generated by Django 5.1.5 on 2025-01-26 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Genero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('rg', models.CharField(max_length=15)),
                ('cpf', models.CharField(max_length=11)),
                ('ctps', models.CharField(max_length=30)),
                ('data_nascimento', models.DateField()),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pessoa_genero', to='Genero.genero')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
