# Generated by Django 5.1.5 on 2025-01-26 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Estado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=32)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cidade_estado', to='Estado.estado')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
