# Generated by Django 5.1.5 on 2025-01-26 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoSalarial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('carga_horaria', models.IntegerField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=18)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hs_pessoa', to='Pessoa.pessoa')),
            ],
            options={
                'ordering': ['data_cadastro'],
            },
        ),
    ]
